set terminal svg size 800,600
set output "gnuplotSplinePlot.svg"

set title "Gnuplot Spline (csplines) Interpolation"
set xlabel "x"
set ylabel "y"
set key top right

# Plot the raw data points and a cubic spline interpolation generated by Gnuplot.
plot "dataPoints.txt" using 1:2 with points pt 7 ps 1.5 title "Data Points", \
     "dataPoints.txt" using 1:2 smooth csplines with lines title "Gnuplot csplines"
